apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: install-chrony
  name: install-chrony
spec:
  selector:
    matchLabels:
      component: install-chrony
      tier: node
  template:
    metadata:
      labels:
        component: install-chrony
        tier: node
    spec:
      #Enable node selector in case you need to run on specific node pool
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - command:
        - nsenter
        - --target
        - "1"
        - --mount
        - --uts
        - --ipc
        - --net
        - --pid
        - --
        - sh
        - -c
        - |
          apt-get update
          apt-get install chrony -y
          chronyc tracking
          cp -pr /etc/chrony/chrony.conf /etc/chrony/chrony.conf.bk
          echo > /etc/chrony/chrony.conf
          echo "# Welcome to the chrony configuration file. See chrony.conf(5) for more" >> /etc/chrony/chrony.conf
          echo "# information about usuable directives." >> /etc/chrony/chrony.conf
          echo "# This will use (up to):" >> /etc/chrony/chrony.conf
          echo "# - 4 sources from ntp.ubuntu.com which some are ipv6 enabled" >> /etc/chrony/chrony.conf
          echo "# - 2 sources from 2.ubuntu.pool.ntp.org which is ipv6 enabled as well" >> /etc/chrony/chrony.conf
          echo "# - 1 source from [01].ubuntu.pool.ntp.org each (ipv4 only atm)" >> /etc/chrony/chrony.conf
          echo "# This means by default, up to 6 dual-stack and up to 2 additional IPv4-only" >> /etc/chrony/chrony.conf
          echo "# sources will be used." >> /etc/chrony/chrony.conf
          echo "# At the same time it retains some protection against one of the entries being" >> /etc/chrony/chrony.conf
          echo "# down (compare to just using one of the lines). See (LP: #1754358) for the" >> /etc/chrony/chrony.conf
          echo "# discussion." >> /etc/chrony/chrony.conf
          echo "#" >> /etc/chrony/chrony.conf
          echo "# About using servers from the NTP Pool Project in general see (LP: #104525)." >> /etc/chrony/chrony.conf
          echo "# Approved by Ubuntu Technical Board on 2011-02-08." >> /etc/chrony/chrony.conf
          echo "# See http://www.pool.ntp.org/join.html for more information." >> /etc/chrony/chrony.conf
          echo "#pool ntp.ubuntu.com        iburst maxsources 4" >> /etc/chrony/chrony.conf
          echo "#pool 0.ubuntu.pool.ntp.org iburst maxsources 1" >> /etc/chrony/chrony.conf
          echo "#pool 1.ubuntu.pool.ntp.org iburst maxsources 1" >> /etc/chrony/chrony.conf
          echo "#pool 2.ubuntu.pool.ntp.org iburst maxsources 2" >> /etc/chrony/chrony.conf
          echo "# This directive specify the location of the file containing ID/key pairs for" >> /etc/chrony/chrony.conf
          echo "# NTP authentication." >> /etc/chrony/chrony.conf
          echo "keyfile /etc/chrony/chrony.keys" >> /etc/chrony/chrony.conf
          echo "# This directive specify the file into which chronyd will store the rate" >> /etc/chrony/chrony.conf
          echo "# information." >> /etc/chrony/chrony.conf
          echo "driftfile /var/lib/chrony/chrony.drift" >> /etc/chrony/chrony.conf
          echo "# Uncomment the following line to turn logging on." >> /etc/chrony/chrony.conf
          echo "#log tracking measurements statistics" >> /etc/chrony/chrony.conf
          echo "# Log files location." >> /etc/chrony/chrony.conf
          echo "logdir /var/log/chrony" >> /etc/chrony/chrony.conf
          echo "# Stop bad estimates upsetting machine clock." >> /etc/chrony/chrony.conf
          echo "maxupdateskew 100.0" >> /etc/chrony/chrony.conf
          echo "# This directive enables kernel synchronisation (every 11 minutes) of the" >> /etc/chrony/chrony.conf
          echo "# real-time clock. Note that it can’t be used along with the 'rtcfile' directive." >> /etc/chrony/chrony.conf
          echo "rtcsync" >> /etc/chrony/chrony.conf
          echo "# Settings come from: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync" >> /etc/chrony/chrony.conf
          echo "refclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0" >> /etc/chrony/chrony.conf
          echo "makestep 1.0 -1" >> /etc/chrony/chrony.conf
          systemctl restart chrony
          while true; do sleep 100000; done
        image: alpine
        imagePullPolicy: IfNotPresent
        name: sysctl-patch
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
